name: webf
description: A W3C standard compliant Web rendering engine based on Flutter.
version: 0.1.0
homepage: https://openwebf.com

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0 # Pure dart module.
  meta: ^1.3.0 # Pure dart module.
  ffi: ^1.0.0 # Pure dart module.
  async: ^2.6.1 # Pure dart module.
  quiver: ^3.0.1+1 # Pure dart module.
  vector_math: ^2.1.0 # Pure dart module.
  connectivity: ^3.0.6 # No AndroidX used.
  shared_preferences: ^2.0.6 # No AndroidX used.

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # NOTE: This new plugin description format is not supported on Flutter's
  # stable channel as of 1.9.1. A plugin published using this format will not
  # work for most clients until the next major stable release.
  # However, it is required in order to declare macOS support.
  plugin:
    platforms:
      android:
        package: com.openwebf.webf
        pluginClass: WebfPlugin
      ios:
        pluginClass: WebfPlugin
      macos:
        pluginClass: WebfPlugin
      linux:
        pluginClass: WebfPlugin
