name: Run Code Linter

on:
  workflow_dispatch:
  push:
    paths:
      - 'bridge/**'

jobs:
  cppcheck:
    runs-on: macos-12
    name: Cppcheck
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run cppcheck
        run: |
          brew install cppcheck
          cd bridge/polyfill
          npm i
          npm run build
          cd ../
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
          cppcheck --project=compile_commands.json -ithird_party --enable=all --suppress=missingIncludeSystem --quiet
        continue-on-error: true

  check_merge_conflict:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Run the actual merge conflict finder
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v3.0
  reformat-bridge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './bridge'
        exclude: './bridge/third_party/*'
        extensions: 'h,cc,c'
        clangFormatVersion: 12
        inplace: True
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

